// This file is autogenerated by hidl-gen. Do not edit manually.
// Source: android.hardware.audio@7.1
// Location: hardware/interfaces/audio/7.1/

#ifndef HIDL_GENERATED_ANDROID_HARDWARE_AUDIO_V7_1_EXPORTED_CONSTANTS_H_
#define HIDL_GENERATED_ANDROID_HARDWARE_AUDIO_V7_1_EXPORTED_CONSTANTS_H_

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    AUDIO_LATENCY_MODE_FREE = 0,
    AUDIO_LATENCY_MODE_LOW = 1,
} audio_latency_mode_t;

#ifdef __cplusplus
}
#endif

#endif  // HIDL_GENERATED_ANDROID_HARDWARE_AUDIO_V7_1_EXPORTED_CONSTANTS_H_
